create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null default 0,
  stock_quantity integer not null default 0,
  category text,
  image_url text,
  description text,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists stock_quantity integer not null default 0;
alter table public.products add column if not exists category text;
alter table public.products add column if not exists image_url text;
alter table public.products add column if not exists description text;
alter table public.products add column if not exists created_at timestamptz not null default now();

create table if not exists public.orders (
  id text primary key,
  date timestamptz not null default now(),
  userEmail text,
  customerName text,
  customerPhone text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric not null default 0,
  shipping numeric not null default 0,
  discount numeric not null default 0,
  total numeric not null default 0,
  couponCode text,
  paymentMethod text,
  paymentProvider text,
  paymentReference text,
  paymentStatus text not null default 'pending',
  paymentReceived boolean not null default false,
  paymentRisk text not null default 'normal',
  deliveryMethod text,
  deliveryEta text,
  deliveryAddress text,
  delivered boolean not null default false,
  approvalStatus text not null default 'pending',
  orderStatus text not null default 'pending',
  trackingNumber text,
  adminNote text
);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;
